### ISSUE TITLE
com_dotnet dla linuxa?

### ISSUE THREAD

**Issue by xblack21** [asocial-media/subiekt-sfera#1]
Witam,

czy stworzone przez ciebie rozwiązanie będzie działać na Unixowych maszynach, czy da rade zastąpić klasę COM - klasą PDO?

Pozdrawiam

**Comment by mstraczkowski** [comment]
Subiekta raczej nie da rady zainstalować na systemie unixowym _(przynajmniej nie w prosty sposób)_

Związku z tym nie widzę możliwości wykorzystania tej biblioteki w środowisku unixowym _(nad czym także ubolewam, bo utrzymanie serwera unixowego jest dużo prostsze i tańsze)_

Moje rozwiązanie służy do komunikacji z zewnętrznym komponentem subiekta:
https://www.insert.com.pl/programy_dla_firm/sprzedaz/subiekt_gt_sfera/opis.html

Natomiast jeżeli chodzi o samo połączenie z bazą danych i wyciąganie z niej informacji to nie widzę problemu, aby wykorzystać wspomniane przez Ciebie PDO lub chociażby http://php.net/manual/en/book.sqlsrv.php i w środowisku unixowym to także będzie działać - aczkolwiek serwer bazy danych Subiekta musi być dostępny na zewnątrz.

Aczkolwiek byłbym ostrożny z operacjami na bazie danych UPDATE / INSERT itd, gdyż łatwo doprowadzić do naruszenia integralności danych przez co Subiekt może odmówić posłuszeństwa - dlatego bezpieczniej jest korzystać z dedykowanego rozwiązania jakim jest Subiekt Sfera _(jeżeli chodzi o manipulowanie danymi)_
